name: 'PR Validation'
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  pr-validation:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/pr-checks.yml@38cd6ebc01e8b5b14ac9a90a5579d04b02e79099
    secrets: inherit
    with:
      subjectPattern: '.+'
